### ISSUE TITLE
"2021 Programming Stats" issues

### ISSUE THREAD

**Issue by MilovanovM** [wakatime/wakatime-blog#12]
Hey guys,

According to the stats "Top operating systems used" (from [here](https://wakatime.com/blog/51-wakatime-2021-programming-stats)):
Windows 16,007,283 (+36%)
Mac 15,716,243 (-43%)
Linux 7,672,866 (+18%)

The total is 39,396,392 hours

It means the previous numbers were:
Windows 11,770,061
Mac 27,572,356
Linux 6,502,428

The total is 45,844,845 hours, am I right?

So, I noticed a couple of weird things here:
-- you're loosing users (14% drop in the total usage time y/y), right?
-- something wrong with the Mac stat. I'd expect increasing numbers in the Mac usage (especially after the M1 processor was introduced), but you're saying that the Mac usage dropped almost twice as much. How is it possible? Maybe a bug in the stat collector (it can't determine an OS version in case a user has an M1 Mac)?

Thanks

**Comment by alanhamlett** [comment]
The percent change is the amount of pie each Operating System has compared to the amount of pie it had last year. It doesn't mean the total Mac hours decreased, just that more devs (who use WakaTime) started using Windows. This is usually because Mac users are early adopters. When WakaTime first started, Mac had almost 50% of the usage and was almost double Windows usage. As WakaTime becomes more well-known, the Windows part of the pie reflects that.

Here's the previous year's operating system stats:

![image](https://user-images.githubusercontent.com/522344/147881317-cccc67e8-c855-4806-b49b-7863b8f7ea27.png)

Mac 15,972,105
Windows 13,197,340
Linux 6,761,196

It looks like Mac did decrease slightly, maybe (guessing) because people upgrade to M1 and forget to re-install the WakaTime plugin on their new Mac.

I expect this trend will continue until WakaTime usage matches a larger platform, like StackOverflow. Here's SackOverflow's [developer survey](https://insights.stackoverflow.com/survey/2021#section-most-popular-technologies-operating-system) which is probably where WakaTime is heading towards:
<img width="1351" alt="Screen Shot 2022-01-02 at 8 08 19 AM" src="https://user-images.githubusercontent.com/522344/147881830-9a283871-3784-467c-b6b6-0023c0cb5a0b.png">

Windows 41.2%
Mac 30.04%
Linux 25.17%

**Comment by MilovanovM** [comment]
Sorry, I didn't get it.
> The percent change is the amount of pie each Operating System has compared to the amount of pie it had last year.

Previous stat from your message in %: Mac 44%, Windows 37%, Linux 19%
Current stat: Mac 40%, Windows 41%, Linux 19%
How the -43% for Mac was calculated?

**Comment by alanhamlett** [comment]
Here's the Python code that creates that OS chart label. It shows the percent change by taking percent from last year and subtracting it from percent from current year:

```python
stat = [x for x in stats['operating_systems'] if x['name'] == 'Mac'][0]
direction = ''
current_percent = stat['sum']['seconds'] / stats['total']['sum']['seconds']
last_percent = last_year_stats[stats_type][stat['name']]['sum']['seconds'] / last_year_stats['total']['sum']['seconds']
change = int(abs(current_percent - last_percent * 100))
if change == 0:
    change = round(round(abs(current_percent - last_percent), 3) * 100, 1)
if current_percent > last_percent:
    direction = '{}{}%'.format('▴' if fmt == 'svg' else '+', change)
if current_percent < last_percent:
    direction = '{}{}%'.format('▾' if fmt == 'svg' else '-', change)
label = '{label} {direction}'.format(
    label=label,
    direction=direction,
)
```

**Comment by MilovanovM** [comment]
Ah, I see the bug now, you forgot to add round brackets
![image](https://user-images.githubusercontent.com/1742065/147885082-b4cbe2ac-fe76-441d-af22-6155960c5b9f.jpeg)

**Comment by alanhamlett** [comment]
Oh, whoops! Thanks for fixing this, it's updated in the chart images on the blog post now.

**Comment by alanhamlett** [comment]
We found another bug in the formula and just re-generated all the images. The bars didn't change, only the percent change label:

```python
from decimal import Decimal

stat = [x for x in stats['operating_systems'] if x['name'] == 'Mac'][0]

direction = ''
current_percent = Decimal(stat['sum']['seconds']) / Decimal(stats['total']['sum']['seconds'])
if last_year_stats['total']['sum']['seconds'] > 0:
    last_percent = Decimal(last_year_stats[stats_type].get(stat['name'], {}).get('sum', {}).get('seconds', 0)) / Decimal(last_year_stats['total']['sum']['seconds'])
else:
    last_percent = Decimal()
if last_percent > 0:
    change = int(abs((current_percent - last_percent) / last_percent * 100))
    if change == 0:
        change = round(abs((current_percent - last_percent) / last_percent * 100), 1)
elif current_percent > 0:
    change = '∞'
else:
    change = 0
if current_percent > last_percent:
    direction = '{}{}%'.format('▴' if fmt == 'svg' else '+', change)
elif current_percent < last_percent:
    direction = '{}{}%'.format('▾' if fmt == 'svg' else '-', change)
else:
    direction = '0%'
label = '{label} {direction}'.format(
    label=label,
    direction=direction,
)
```
